# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16jMoyrUwk67Gs0a-eE_ExI1GI34sNS2R
"""



import discord, sqlite3, os, csv, io, datetime, asyncio
from collections import Counter
from discord.ext import commands
import anthropic

# Removed Google Colab imports and Drive mounting since they are incompatible with Render.



import sqlite3
import os

# Using local project directory instead of Google Drive
DB_PATH = "intel.db"
conn = sqlite3.connect(DB_PATH, check_same_thread=False)
cursor = conn.cursor()

# Ensure the base table exists first
cursor.execute("""CREATE TABLE IF NOT EXISTS reports (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    org TEXT NOT NULL,
    action TEXT NOT NULL,
    location TEXT DEFAULT 'unknown',
    notes TEXT DEFAULT '',
    reported_by TEXT,
    anonymous INTEGER DEFAULT 0,
    timestamp TEXT NOT NULL
)""")

# Check for missing columns and add them one by one
cursor.execute("PRAGMA table_info(reports)")
existing_cols = [row[1] for row in cursor.fetchall()]

migrations = [
    ('verified', 'INTEGER DEFAULT 0'),
    ('tags', 'TEXT DEFAULT ""'),
    ('lat', 'REAL'),
    ('lon', 'REAL')
]

for col_name, col_type in migrations:
    if col_name not in existing_cols:
        print(f"Migrating: Adding column {col_name}")
        cursor.execute(f"ALTER TABLE reports ADD COLUMN {col_name} {col_type}")

# Settings and Watches tables
cursor.execute("CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY, value TEXT)")
cursor.execute("CREATE TABLE IF NOT EXISTS watches (keyword TEXT PRIMARY KEY, channel_id TEXT)")

conn.commit()
DEFAULT_ORG = "The Lab"
print("Database prepared and migrations applied.")

import discord
from discord.ext import commands
import anthropic
import datetime
import asyncio
import sqlite3
import csv
import io
import folium
import os
from collections import Counter

# Safely handle google.colab imports for local/Render deployment compatibility
try:
    from google.colab import userdata, drive, files
    HAS_COLAB = True
except ImportError:
    HAS_COLAB = False
    class UserdataMock:
        def get(self, key):
            return os.environ.get(key)
    userdata = UserdataMock()

# Define intents BEFORE creating the bot instance
intents = discord.Intents.default()
intents.message_content = True

bot = commands.Bot(command_prefix="!", intents=intents)

anthropic_api_key = userdata.get("ANTHROPIC_API_KEY")
client = anthropic.AsyncAnthropic(api_key=anthropic_api_key) if anthropic_api_key else None

def get_setting(key):
    row = conn.execute("SELECT value FROM settings WHERE key = ?", (key,)).fetchone()
    return row[0] if row else None

def set_setting(key, value):
    conn.execute("INSERT OR REPLACE INTO settings (key, value) VALUES (?, ?)", (key, str(value)))
    conn.commit()

def check_access(interaction):
    required = get_setting("required_role")
    if required and not any(r.name.lower() == required.lower() for r in interaction.user.roles):
        return False
    return True

# --- core report / track ---
@bot.tree.command(name="report", description="File a report on activity")
async def report(interaction: discord.Interaction, action: str, org: str = DEFAULT_ORG, location: str = "unknown", notes: str = "", anonymous: bool = False, tags: str = "", lat: float = None, lon: float = None):
    await interaction.response.defer(ephemeral=True)
    if not check_access(interaction):
        await interaction.followup.send("❌ Permission denied.", ephemeral=True)
        return
    ts = datetime.datetime.now(datetime.timezone.utc).isoformat()
    reported_by = "anonymous" if anonymous else str(interaction.user)
    try:
        params = (org, action, location, notes, reported_by, int(anonymous), tags or "", lat, lon, ts)
        cursor = conn.execute("INSERT INTO reports (org, action, location, notes, reported_by, anonymous, tags, lat, lon, timestamp) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", params)
        conn.commit()
        report_id = cursor.lastrowid
        await interaction.followup.send(f"✅ Report logged as `#{report_id}` for **{org}**.", ephemeral=True)

        # Check watches
        watches = conn.execute("SELECT keyword, channel_id FROM watches").fetchall()
        for kw, ch_id in watches:
            if kw.lower() in action.lower() or kw.lower() in notes.lower():
                try:
                    channel = bot.get_channel(int(ch_id)) or await bot.fetch_channel(int(ch_id))
                    if channel:
                        await channel.send(f"🚨 **Watch Alert!** Keyword `{kw}` matched in report `#{report_id}` ({org} - {action})")
                except Exception:
                    pass
    except Exception as e:
        await interaction.followup.send(f"❌ Database Error: {e}", ephemeral=True)

@bot.tree.command(name="track", description="Show recent tracked activity")
async def track(interaction: discord.Interaction, org: str = DEFAULT_ORG, limit: int = 10):
    await interaction.response.defer(ephemeral=True)
    if not check_access(interaction):
        await interaction.followup.send("❌ No permission.", ephemeral=True); return
    rows = conn.execute("SELECT id, action, location, timestamp FROM reports WHERE lower(org) = lower(?) ORDER BY id DESC LIMIT ?", (org, limit)).fetchall()
    if not rows:
        await interaction.followup.send(f"No reports on **{org}** yet.", ephemeral=True); return
    lines = [f"• `#{r[0]}` **{r[1]}** — {r[2]} ({r[3][:16]})" for r in rows]
    await interaction.followup.send(embed=discord.Embed(title=f"Intel on {org}", description="\n".join(lines), color=discord.Color.red()))

GUILD_ID = 1549521458320113684  # your server ID

@bot.event
async def on_ready():
    guild = discord.Object(id=GUILD_ID)
    bot.tree.clear_commands(guild=guild)   # wipe the server-side copies
    await bot.tree.sync(guild=guild)        # push the empty list to the guild
    await bot.tree.sync()                   # keep the global set
    print(f"Online as {bot.user}")

import asyncio
import os

# The bot and its intents are already defined in cell NEniaViAX2Zx.
# The on_ready event is also already registered in cell qq9wiZGOccRd.
# We just need to run the bot instance that has already been set up.

try:
    cursor = conn.cursor()
    cursor.execute("PRAGMA table_info(reports)")
    columns = [row[1] for row in cursor.fetchall()]

    # Ensure all required columns exist
    for col, ctype in [('tags', 'TEXT'), ('verified', 'INTEGER'), ('lat', 'REAL'), ('lon', 'REAL')]:
        if col not in columns:
            conn.execute(f"ALTER TABLE reports ADD COLUMN {col} {ctype}")
    conn.commit()
    print("Database schema verified.")
except Exception as e:
    print(f"Database check failed: {e}")

# Asynchronous main execution designed for both Colab and local Python scripts (Render)
async def main():
    token = os.environ.get("DISCORD_BOT_TOKEN") # Get token from environment variables
    if not token: # If not set as env variable, try Colab secrets
        try:
            from google.colab import userdata
            token = userdata.get("DISCORD_BOT_TOKEN")
        except Exception:
            print("DISCORD_BOT_TOKEN not found in environment or Colab secrets.")
            return

    if token:
        async with bot:
            await bot.start(token)
    else:
        print("Discord bot token is missing. Please set DISCORD_BOT_TOKEN in environment variables or Colab secrets.")

if __name__ == "__main__":
    # Run asyncio loop safely without throwing top-level awaits errors
    try:
        loop = asyncio.get_event_loop()
        if loop.is_running():
            asyncio.ensure_future(main())
        else:
            asyncio.run(main())
    except Exception as e:
        print(f"Failed to start the bot runner loop: {e}")
